name: Build and Upload Electron App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with electron-vite build
        run: npm run dist

      - name: Get release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "latest";
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            });
            core.setOutput("upload_url", release.data.upload_url);

      - name: Upload exe asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/th123lagchecker.exe
          asset_name: th123lagchecker.exe
          asset_content_type: application/octet-stream
